"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { EmailCaptureDialog } from "@/components/shared/email-capture-dialog";

const PRINT_CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: system-ui, -apple-system, sans-serif;
    color: #1a1a1a;
    padding: 2rem;
    font-size: 13px;
    line-height: 1.5;
  }
  .print-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 1.5rem;
    padding-bottom: 1rem;
    border-bottom: 2px solid #2563eb;
  }
  .print-header h1 {
    font-size: 20px;
    font-weight: 700;
    color: #1a1a1a;
  }
  .print-header .subtitle {
    font-size: 12px;
    color: #6b7280;
    margin-top: 2px;
  }
  .print-header .branding {
    text-align: right;
    font-size: 11px;
    color: #6b7280;
  }
  .print-header .branding .site {
    font-weight: 600;
    color: #2563eb;
  }

  .section { margin-bottom: 1.5rem; }
  .section-title {
    font-size: 14px;
    font-weight: 700;
    margin-bottom: 0.5rem;
    color: #1e3a5f;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  table {
    border-collapse: collapse;
    width: 100%;
    margin-bottom: 0.75rem;
    font-size: 12px;
  }
  th, td {
    border: 1px solid #e5e7eb;
    padding: 6px 10px;
    text-align: right;
  }
  th {
    background: #f3f4f6;
    font-weight: 600;
    text-align: left;
    color: #374151;
  }
  td:first-child, th:first-child { text-align: left; }
  tr:nth-child(even) { background: #f9fafb; }

  .summary-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    gap: 12px;
    margin-bottom: 1rem;
  }
  .summary-card {
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    padding: 10px 14px;
  }
  .summary-card .label {
    font-size: 11px;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.3px;
    margin-bottom: 2px;
  }
  .summary-card .value {
    font-size: 16px;
    font-weight: 700;
    color: #1a1a1a;
  }
  .summary-card .sublabel {
    font-size: 10px;
    color: #9ca3af;
    margin-top: 2px;
  }
  .summary-card.highlight {
    border-color: #2563eb;
    background: #eff6ff;
  }
  .summary-card.highlight .value { color: #1d4ed8; }
  .summary-card.success { border-color: #16a34a; background: #f0fdf4; }
  .summary-card.success .value { color: #15803d; }
  .summary-card.danger { border-color: #dc2626; background: #fef2f2; }
  .summary-card.danger .value { color: #b91c1c; }
  .summary-card.warning { border-color: #d97706; background: #fffbeb; }
  .summary-card.warning .value { color: #b45309; }

  .note {
    font-size: 11px;
    color: #6b7280;
    font-style: italic;
    margin-top: 0.5rem;
  }

  .print-footer {
    margin-top: 2rem;
    padding-top: 0.75rem;
    border-top: 1px solid #e5e7eb;
    font-size: 10px;
    color: #9ca3af;
    text-align: center;
  }

  @media print {
    body { padding: 1rem; }
    .section { page-break-inside: avoid; }
  }
`;

function buildPrintShell(title: string, content: string): string {
  const date = new Date().toLocaleDateString("en-PH", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title} — Startup Finance Toolkit</title>
  <style>${PRINT_CSS}</style>
</head>
<body>
  <div class="print-header">
    <div>
      <h1>${title}</h1>
      <div class="subtitle">Generated on ${date}</div>
    </div>
    <div class="branding">
      <div class="site">Startup Finance Toolkit</div>
      <div>startupfinance.tools</div>
    </div>
  </div>
  ${content}
  <div class="print-footer">
    Generated by Startup Finance Toolkit &middot; startupfinance.tools &middot; ${date}
  </div>
</body>
</html>`;
}

export function summaryCard(
  label: string,
  value: string,
  opts?: { sublabel?: string; variant?: "highlight" | "success" | "danger" | "warning" }
): string {
  const cls = opts?.variant ? ` ${opts.variant}` : "";
  return `<div class="summary-card${cls}">
    <div class="label">${label}</div>
    <div class="value">${value}</div>
    ${opts?.sublabel ? `<div class="sublabel">${opts.sublabel}</div>` : ""}
  </div>`;
}

export function section(title: string, content: string): string {
  return `<div class="section">
    <div class="section-title">${title}</div>
    ${content}
  </div>`;
}

export function table(headers: string[], rows: string[][]): string {
  const thead = headers.map((h) => `<th>${h}</th>`).join("");
  const tbody = rows
    .map((row) => `<tr>${row.map((c) => `<td>${c}</td>`).join("")}</tr>`)
    .join("");
  return `<table><thead><tr>${thead}</tr></thead><tbody>${tbody}</tbody></table>`;
}

interface ExportPDFButtonProps {
  filename?: string;
  buildPrintContent: () => string;
  enableEmailCapture?: boolean;
  /** @deprecated Use buildPrintContent instead */
  elementId?: string;
}

export function ExportPDFButton({
  filename = "export",
  buildPrintContent,
  enableEmailCapture = false,
}: ExportPDFButtonProps) {
  const [showDialog, setShowDialog] = useState(false);

  const doPrint = () => {
    const content = buildPrintContent();
    const html = buildPrintShell(filename, content);

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  };

  const handleClick = () => {
    if (
      enableEmailCapture &&
      !sessionStorage.getItem("pdf-email-captured")
    ) {
      setShowDialog(true);
    } else {
      doPrint();
    }
  };

  const handleEmailSuccess = () => {
    sessionStorage.setItem("pdf-email-captured", "true");
  };

  const handleDialogChange = (open: boolean) => {
    setShowDialog(open);
    if (!open) {
      doPrint();
    }
  };

  return (
    <>
      <Button variant="outline" size="sm" onClick={handleClick}>
        <Download className="h-4 w-4 mr-2" />
        Export PDF
      </Button>
      {enableEmailCapture && (
        <EmailCaptureDialog
          open={showDialog}
          onOpenChange={handleDialogChange}
          onSuccess={handleEmailSuccess}
        />
      )}
    </>
  );
}
